//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDASSIGN
    {
        public long RECNUM { get; set; }
        public int ID { get; set; }
        public decimal CLIENT_ID { get; set; }
        public short UNIT_ID { get; set; }
        public string SUB_UNIT_ID { get; set; }
        public int CLTRT_ID { get; set; }
        public decimal SERVER_ID { get; set; }
        public string TTEAM_ID { get; set; }
        public System.DateTime DATE_OPENED { get; set; }
        public System.DateTime DATE_CLOSED { get; set; }
        public string ADMIT_FLAG { get; set; }
        public string TYPE_FLAG { get; set; }
        public string REAS_ID { get; set; }
        public string TRAN_FLAG { get; set; }
        public string TRAN_APPROVE_F { get; set; }
        public Nullable<int> TRAN_FR_ASS_ID { get; set; }
        public Nullable<int> TRAN_TO_ASS_ID { get; set; }
        public Nullable<short> OPEN_HOUR { get; set; }
        public string OPEN_MINUTE { get; set; }
        public Nullable<short> CLOSE_HOUR { get; set; }
        public string CLOSE_MINUTE { get; set; }
        public string AGENCY { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string PHONE { get; set; }
        public string CONTACT_NAME { get; set; }
        public string REF_PROV_ID { get; set; }
        public string REF_PROV_LNAME { get; set; }
        public string NOT_USED_30 { get; set; }
        public string DEST_PROV_ID { get; set; }
        public string DEST_PROV_NAME { get; set; }
        public string DEST_PROV_TYPE { get; set; }
        public string REL_ID { get; set; }
        public string LIVING_ID { get; set; }
        public Nullable<short> THER_LEAVE_DAYS { get; set; }
        public string NY_DISCH_STAT { get; set; }
        public Nullable<decimal> PAT_PART_AMT { get; set; }
        public string SING_PAR_FAM_F { get; set; }
        public string USTF_PATIENT__ { get; set; }
        public Nullable<short> NM_LOC_OPENED { get; set; }
        public Nullable<short> NM_LOC_CLOSED { get; set; }
        public Nullable<short> PAT_STAT_ID { get; set; }
        public string ASSCAT_ID { get; set; }
        public string CSI_ADM_CRIT { get; set; }
        public string CSI_LEGAL_ADM { get; set; }
        public string CSI_LEGAL_DC { get; set; }
        public Nullable<int> ENTERED_BY_ID { get; set; }
        public Nullable<System.DateTime> ENTERED_DATE { get; set; }
        public Nullable<int> DELETED_BY_ID { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public string VOID_FLAG { get; set; }
        public string MCAUTH_DEL_FLAG { get; set; }
        public string OSHPD_ADMSITE { get; set; }
        public Nullable<short> OSHPD_ADMROUTE { get; set; }
        public Nullable<short> OSHPD_ADMTYPE { get; set; }
        public string OSHPD_DNR { get; set; }
        public string WA_PROG_ID { get; set; }
        public Nullable<System.DateTime> WA_PROG_BEG_DT { get; set; }
        public Nullable<System.DateTime> WA_PROG_END_DT { get; set; }
        public Nullable<decimal> REF_PROV_NPI { get; set; }
        public string REF_PROV_LTYPE { get; set; }
        public string REF_PROV_FNAME { get; set; }
        public string CARE_LOC_CODE { get; set; }
        public string TOC_FLAG { get; set; }
    }
}
