//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical
    {
        public long incidentMedicalId { get; set; }
        public long incidentId { get; set; }
        public long medStaffId { get; set; }
        public System.DateTime medAssmntDate { get; set; }
        public string medAssmnt { get; set; }
        public System.DateTime createdStamp { get; set; }
        public string createdStation { get; set; }
        public int statusId { get; set; }
    }
}
