//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportIncident
    {
        public long reportIncidentTypeId { get; set; }
        public long incidentId { get; set; }
        public int incidentTypeId { get; set; }
        public string incidentInfo { get; set; }
    }
}
