//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restraint
    {
        public long IncidentRestraintId { get; set; }
        public long incidentId { get; set; }
        public string restraintType { get; set; }
        public System.DateTime restraintStart { get; set; }
        public System.DateTime restraintEnd { get; set; }
        public double restraintLength { get; set; }
        public string postProcess { get; set; }
    }
}
